### ISSUE TITLE
💃🏾 Create the 'How To Contribute' file

### ISSUE THREAD

**Issue by izzycodes02** [xiacodes/Froggie-To-Do#5]
## 💻 Desciption
The project needs its own .md file of how to contribute to the project! This issue involves using your HTML/Markdown and writing skills! This issue is great and easy for people starting off by contributing! 🥰🤗👍🏾

## 🎯 Task
As you can see, the readme.md file is long because of the **'How To Contribute'** information. Organisation within a project is key soooo:
- [ ] Create a new .md file
- [ ] Add all the content needed for the file - you can copy and paste the text from the **readme.md** or/and add your own text!
- [ ] Save it
- [ ] Have the **readme.md** file link to the new file!

Remember, only on the **'How to Contribute'** section (up to the **'Meet the Contributors'** section), the rest is okay for now!

## 🙋🏾‍♀️ Want to start this task?
Comment that you have interest and basically follow the instructions of the **'How To Contribute'**! There will be a branch from this issue for you to work towards! Once done, make a pull request! 

Any questions, do let me know! Thank you for wanting to help! 🐸💗

**Comment by yehoki** [comment]
Hey, if it's still possible would it be possible to get assigned to this?

**Comment by izzycodes02** [comment]
> Hey, if it's still possible would it be possible to get assigned to this? 

Hiya! Yes, you can! I made the branch for this issue so go ahead and start! Best of luck! 😊👍🏾

**Comment by yehoki** [comment]
> Hiya! Yes, you can! I made the branch for this issue so go ahead and start! Best of luck! 😊👍🏾

All done - My first time contributing not sure if you wanted me to fork it from the branch itself or from main - let me know if there are any issues and I'll be happy to correct it

**Comment by izzycodes02** [comment]
Oh my goodness @yehoki, you did an excellent job! Thank you for helping! The file looks great, don't worry! 🤗👍🏾

I'll tick this off as a completed Issue! 🎉

Also, if you're good with your HTML/CSS/JavaScript skills (some or all 3), there's a project I am working on which is just making a simple quiz game! If you want to continue contributing to projects, you can work on it! The project is [The Quiz App](https://github.com/mmnldm/thequizapp) 🙋🏾‍♀️ We are all beginners and want to work on contributing! Let me know if that's something that interests you!
